spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  #spring.datasource.url=jdbc:mysql://localhost:3306/demojwt?createDatabaseIfNotExist=true
  #spring.datasource.username=silentlove
  #spring.datasource.password=loveyou4everA@
spring.datasource.url=jdbc:mysql://MySQL/demojwt?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root!123
  
  #JPA + Hibernate
spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
