server:
  port: 8083
spring:
  application:
    name: orders
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices_order
    username: silentlove
    password: loveyou4everA@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true