server:
    port: 8089
spring:
    application:
        name: customer
    datasource:
        password: loveyou4everA@
        url: jdbc:mysql://localhost:3306/customer
        username: silentlove
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        generate-ddl: true
    zipkin:
        base-url: http://zipkin:9411
    rabbitmq:
        addresses: rabbitmq:5672
eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: false