server:
    port: 8089
spring:
    application:
        name: auth-service
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/microservices_auth
        username: silentlove
        password: loveyou4everA@
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: true
eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: false